extends Node
## Loc — простая локализация по ключам (ТЗ §29). По умолчанию русский.
## Весь UI-текст идёт через t("key") — никаких хардкод-строк в логике.

signal language_changed

var lang := "ru"

const DATA := {
	"ru": {
		# Навигация (§5.2 — RU-сборка)
		"nav.throne": "Трон",
		"nav.provinces": "Эялеты",
		"nav.institutions": "Институты",
		"nav.events": "Летопись",
		"nav.dynasty": "Династия",
		# Ресурсы (§8)
		"res.hazna": "Хазна",
		"res.stability": "Стабильность",
		"res.army": "Армия",
		"res.loyalty": "Лояльность",
		"res.food": "Еда",
		"res.opposition": "Оппозиция",
		"res.fracture": "Недовольство",
		"res.development": "Развитие",
		"res.pressure": "Давление",
		"res.legitimacy": "Легитимность",
		"chr.legit_saved": "Легитимность сохранена",
		"leg.pressure": "Внешнее давление держав. Растёт со временем; ускоряет падение стабильности, расход еды и распад провинций.",

		"sys.coup": "Дворцовый переворот! Вас свергли.",
		"over.title": "Вас свергли",
		"over.sub": "Толпа и янычары низложили султана. Ваше правление окончено — но новый дом может подняться из пепла.",
		"over.restart": "Начать сначала",

		"set.legend": "Показатели",
		"leg.hazna": "Казна. Копится за касания Печати; тратится на вложения, институты и решения событий.",
		"leg.stability": "Порядок в державе. Падает от внешнего давления и трещин; при 0 оппозиция растёт стремительно.",
		"leg.army": "Военная мощь. Нужна для подавления провинций и жёстких вариантов в событиях.",
		"leg.loyalty": "Верность подданных. Низкая — ускоряет трещины провинций и рост оппозиции.",
		"leg.food": "Продовольствие. Зависит от развития провинций; мало — падает стабильность и начинаются бунты.",
		"leg.opposition": "Сила недовольных. Каждое решение её двигает; растёт при хаосе. 100% — дворцовый переворот.",

		# Трон
		"throne.epigraph": "«Стабильность государства держится на острие сабли.»",
		"throne.tap": "Коснись Печати — наполни казну",
		"throne.reform": "Реформа Низам-ı Джедид",
		"throne.per_click": "за касание",
		"throne.frenzy_cd": "×%d через %d с",
		"throne.taps": "Касаний",
		# Эялеты
		"prov.revenue": "ХАЗНА ЗА КАСАНИЕ",
		"prov.per_tap": "за касание",
		"prov.rising": "Империя крепнет",
		"prov.declining": "Империя угасает",
		"prov.governed": "Управляемые эялеты",
		"prov.souls": "душ",
		"prov.invest": "Вложить",
		"prov.suppress": "Подавить",
		"prov.fracture": "Недовольство",
		"prov.lost": "ОТКОЛОЛАСЬ",
		"prov.core": "Ядро империи",
		# Институты
		"inst.title": "Имперские институты",
		"inst.epigraph": "Опоры Дома Османа должны выдержать ветры перемен.",
		"inst.level": "Уровень",
		"inst.rank": "Ранг",
		"inst.upgrade": "Развить",
		"inst.unlock": "Открыть доступ",
		"inst.high_risk": "ВЫСОКИЙ РИСК",
		"inst.accelerate": "УСКОРИТЬ РЕФОРМУ",
		"inst.progress": "прогресс",
		"inst.reform_done": "Реформа завершена",
		# Летопись / события
		"ev.title": "Летопись",
		"ev.subtitle": "Имперская хроника",
		"ev.epigraph": "«Каждое решение прокладывает путь Дома Османа.»",
		"ev.empty": "Хроника пуста. История ещё не написана.",
		"ev.decree": "Имперский декрет",
		"ev.requirement": "Требование",
		"ev.cost": "Цена",
		"prov.provisions": "Снабжение",
		"prov.buy_food": "Купить зерно",
		"prov.per_unit": "шт",
		"prov.granaries": "Амбары",
		"prov.upgrade_granaries": "Улучшить амбары",
		"prov.razed": "город разрушен, развитие утрачено",
		"ev.envoy_title": "Прибыл гонец",
		"ev.envoy_sub": "К трону доставлено запечатанное письмо. Оно ждёт вашего слова, повелитель.",
		"ev.open_letter": "Открыть письмо",
		"ev.your_state": "Ваше положение",
		"ev.hold_hint": "Зажми вариант — увидишь исход",
		"ev.result": "Возможный исход",

		# Династия
		"dyn.title": "Высокая Порта",
		"dyn.protector": "ЗАЩИТНИК ПРЕДЕЛОВ",
		"dyn.prestige": "ИМПЕРСКИЙ ПРЕСТИЖ",
		"dyn.next_rank": "Следующий ранг",
		"dyn.decrees": "Декреты наследия",
		"dyn.bought": "ПОЛУЧЕНО",
		"dyn.buy": "КУПИТЬ",
		"dyn.family": "Семейное древо",
		"throne.diplomacy": "Дипломатия",
		"diplo.title": "Дипломатия",
		"diplo.hint": "Отношения тают со временем — их нужно поддерживать золотом. Плохие отношения — дорогой хлеб и стычки на границе.",
		"diplo.improve": "Улучшить",
		"diplo.worsen": "Ухудшить",
		"diplo.eff.trade_bad": "Пути закрыты: +%d%% к цене хлеба",
		"diplo.eff.trade_mid": "Тяжёлые пошлины: +%d%% к цене хлеба",
		"diplo.eff.trade_ok": "Торговля свободна",
		"diplo.eff.vassal": "Вассал: платит дань, шлёт войска",
		"diplo.eff.border_bad": "Приграничные набеги неизбежны",
		"diplo.eff.border_mid": "Стычки на границе учащаются",
		"diplo.eff.border_ok": "Граница спокойна",
		"diplo.vassal": "Вассал",
		"diplo.tariff": "Пошлины на чумацкие обозы: +%d%% к цене хлеба",
		"diplo.tariff_none": "Торговые шляхи открыты — хлеб идёт без пошлин",
		"diplo.moscow": "Московское государство",
		"diplo.poland": "Речь Посполитая",
		"diplo.austria": "Австрия",
		"diplo.persia": "Сефевидская Персия",
		"diplo.crimea": "Крымское ханство",
		"dyn.you": "Султан (вы)",
		"dyn.reigned_until": "правил до",
		"dyn.spouse": "Супруга",
		"dyn.heir": "Наследник",
		"dyn.no_spouse": "Невеста не найдена",
		"dyn.empty_heir": "Нет наследника",
		"dyn.deceased": "погиб",
		"dyn.deceased_f": "усопшая",
		"dyn.wed": "Свадьба",
		"dyn.wed_open": "Сосватать",
		"dyn.no_wife": "Нет жены",
		"dyn.seek_title": "Искать жену?",
		"dyn.seek_body": "Объявить поиск невесты по знатным домам? Это будет стоить 10 000 хазны, после чего начнут приходить предложения руки.",
		"dyn.seek_pay": "Оплатить",
		"dyn.seek_cancel": "Отмена",
		"dyn.seek_cta": "Найти жену",
		"dyn.seeking": "Поиск невесты…",
		"dyn.seek_started": "Объявлен поиск невесты — ждите предложений.",
		"dyn.seek_poor": "Недостаточно хазны на поиск жены.",
		"ev.skirmish_losses": "Потери в стычке — доверие армии пошатнулось:",
		"menu.title": "Закат Полумесяца",
		"menu.play": "Играть",
		"wheel.hazna_10k": "10 000 ⚜",
		"wheel.energy_2d": "⚡ 2 дня",
		"wheel.debt_10k": "− 10 000 ⚜",
		"wheel.no_ads": "Без рекламы",
		"wheel.wife_coupon": "Купон − 80%",
		"wheel.amnesty": "Амнистия",
		"wheel.ad": "Реклама",
		"wheel.debt_20k": "− 20 000 ⚜",
		"wheel.diplo_coupon": "Купон посла",
		"wheel.ad2": "Реклама",
		"wheel.debt_50k": "− 50 000 ⚜",
		"wheel.energy_1d": "⚡ 1 день",
		"menu.wheel": "Колесо удачи",
		"menu.settings": "Настройки",
		"menu.donate": "Донат",
		"menu.wheel_ready": "Доступно!",
		"menu.wheel_in": "Через %s",
		"wheel.title": "Колесо удачи",
		"wheel.spin": "Крутить колесо",
		"wheel.back": "Назад",
		"wheel.won": "Выигрыш:",
		"wheel.next": "Следующее вращение через %s",
		"donate.title": "Поддержка игры",
		"donate.body": "Спасибо, что играете! Поддержать разработку можно просмотром рекламы или пожертвованием.",
		"donate.ad": "Смотреть рекламу (+1 000 \u269C)",
		"donate.ad_soon": "Скоро — после подключения рекламы",
		"donate.support": "Поддержать разработку",
		"energy.title": "Энергия",
		"energy.full_in": "Полная через %s",
		"energy.empty": "Энергия исчерпана — султану нужен отдых.",
		"energy.unlim": "Безлимит: %s",
		"debt.forgiven": "Долги прощены!",
		"debt.amnesty_kept": "Амнистия получена — сработает при первом долге.",
		"ads.stub": "(тест) Награда выдана — реклама подключится позже.",
		"ads.not_ready": "Реклама пока недоступна.",
		"ads.energy": "Полная энергия за ролик",
		"wheel.respin": "Ещё раз — за ролик",
		"wheel.double": "Удвоить приз — за ролик",
		"offline.double": "Удвоить за ролик",
		"over.second": "Второй шанс — за ролик",
		"donate.burn_debt": "Сжечь долг — за ролик",
		"iap.title": "Покупки",
		"iap.soon": "Покупки появятся после публикации в Google Play.",
		"iap.noads": "Убрать рекламу навсегда — $2.99",
		"iap.starter": "Стартовый набор — $1.99",
		"iap.hazna1": "Кошель хазны (20 000) — $0.99",
		"iap.hazna2": "Сундук хазны (40 000) — $2.99",
		"iap.hazna3": "Казна паши (100 000) — $7.99",
		"iap.firman": "Золотой фирман: +25% с касаний — $3.99",
		"daily.title": "Ежедневная награда:",
		"daily.d1": "+1 500 хазны",
		"daily.d2": "энергия восстановлена",
		"daily.d3": "колесо удачи готово",
		"quest.done": "Задание выполнено:",
		"quest.plague": "Пережить мор",
		"quest.inst": "Институт 3-го уровня",
		"quest.gen3": "Три поколения династии",
		"quest.staff_cost": "Для входа в военный совет нужно %s ⚜",
		"dyn.wife_lost": "Погибла жена",
		"dyn.born": "Рождён наследник",
		"dyn.died": "Погиб наследник",
		"dyn.family_hint": "Жён выбирают через редкие события — до четырёх в гареме; жену можно потерять (чума, бунт). Сын-наследник рождается в событии; повзрослев, он может взойти на трон — по вашей воле или захватив его силой при высокой оппозиции.",
		"dyn.new_reign": "Передать Печать наследнику",
		"dyn.new_reign_hint": "Возвести взрослого сына на трон и обратить достижения в Имперский престиж. Декреты и престиж сохранятся, дальше играем за сына.",
		"dyn.gain": "Престижа за правление",
		"dyn.heir_ready": "наследник · готов к трону",
		"dyn.heir_growing": "Наследник ещё юн — он сможет взойти на трон, когда повзрослеет.",
		"dyn.need_heir": "Сначала нужен сын-наследник — он родится в одном из событий.",
		"dyn.crisis_pass": "Страна в кризисе. Передайте Печать сыну, пока он не взял трон силой.",
		"dyn.no_adult_heir": "Нет взрослого наследника для трона.",
		"dyn.future_wife": "будущая жена",
		"dyn.consort": "супруга",
		"dyn.usurp": "Сын захватил трон!",
		"dyn.new_sultan": "Новый султан:",
		"dyn.sultan_prefix": "Султан",
		# Настройки
		"set.title": "Настройки",
		"set.language": "Язык",
		"set.music": "Музыка",
		"notif.energy": "Батарея заряжена — государство ждёт вас!",
		"notif.day1": "О великий падишах, игра ждёт вас!",
		"notif.day2": "Янычары бунтуют — ПАДИШАХ, ГДЕ ВЫ???",
		"notif.day3": "Империя в огне — где султан?",
		"notif.day4": "Диван собрался без вас — ждут вашего слова.",
		"notif.day5": "Гарем в тревоге, наследник плачет — вернитесь, повелитель.",
		"notif.day6": "Гонец у ворот с печатью — только султан вправе её сломать.",
		"notif.day7": "Оппозиция шепчется по углам… кто-то должен их услышать.",
		"notif.day8": "Казна пустеет, амбары молчат. Держава ждёт хозяина.",
		"notif.day9": "На минарете вновь звучит азан — не пора ли вернуться?",

		"load.q1": "«Стабильность государства держится на острие сабли.»",
		"load.q2": "«Кто держит казну — держит и корону.»",
		"load.q3": "«Империя велика, пока султан не спит.»",
		"load.q4": "«Хлеб дороже золота, когда амбары пусты.»",
		"load.q5": "«У янычар два котла: один — для плова, второй — для мятежа.»",
		"load.q6": "«Казак идёт за добычей — паша идёт за казаком.»",
		"load.q7": "«Мудрый султан слушает диван, но решает сам.»",
		"load.q8": "«Оппозиция шепчет, пока голод не заставит её кричать.»",
		"load.q9": "«Дом Османа стоит на трёх опорах: вере, войске и хазне.»",
		"load.q10": "«Гонец с плохой вестью скачет быстрее гонца с хорошей.»",
		"load.q11": "«Провинция без наместника — как конь без узды.»",
		"load.q12": "«Кто торопится наследовать — тот роет себе могилу.»",
		"load.q13": "«Мор не спрашивает разрешения войти во дворец.»",
		"load.q14": "«Улица накормлена — улица молчит.»",
		"load.q15": "«Империя падает не от врага, а от собственной тени.»",
		"load.progress": "Загрузка",
		"set.fps": "Кадры/сек",
		"set.voice": "Озвучка",
		"set.sfx": "Звуки",
		"set.on": "Вкл",
		"set.off": "Выкл",
		"set.reset": "Сбросить прогресс",
		"set.about": "Об игре",
		"set.close": "Закрыть",
		"set.about_text": "Sunset of the Crescent — мобильная стратегия об управляемом умирании Османской империи. Художественное произведение по мотивам реальных событий. ТЗ v1.1.",
		"set.offline": "Пока тебя не было, казна пополнялась:",
		# Общее
		"common.year": "ГОД",
		"common.confirm": "Подтвердить",
		"common.cancel": "Отмена",
	},
	"en": {
		"nav.throne": "Throne",
		"nav.provinces": "Provinces",
		"nav.institutions": "Institutions",
		"nav.events": "Events",
		"nav.dynasty": "Dynasty",
		"res.hazna": "Hazna",
		"res.stability": "Stability",
		"res.army": "Army",
		"res.loyalty": "Loyalty",
		"res.food": "Food",
		"res.opposition": "Opposition",
		"res.fracture": "Unrest",
		"res.development": "Development",
		"res.pressure": "Pressure",
		"res.legitimacy": "Legitimacy",
		"chr.legit_saved": "Legitimacy Preserved",
		"leg.pressure": "Foreign pressure on the empire. Rises over time; speeds stability loss, food drain and province collapse.",

		"sys.coup": "Palace coup! You have been overthrown.",
		"over.title": "You Have Been Overthrown",
		"over.sub": "The mob and the Janissaries have deposed the Sultan. Your reign is over — but a new house may rise from the ashes.",
		"over.restart": "Start over",

		"set.legend": "Indicators",
		"leg.hazna": "Treasury. Earned by tapping the Seal; spent on investments, institutions and event choices.",
		"leg.stability": "Order in the realm. Falls from outside pressure and fractures; at 0 opposition surges fast.",
		"leg.army": "Military power. Needed to suppress provinces and unlock harsh event options.",
		"leg.loyalty": "Loyalty of subjects. When low it speeds province fractures and opposition.",
		"leg.food": "Food supply. Driven by province development; when low, stability drops and riots begin.",
		"leg.opposition": "Strength of the discontent. Every decision shifts it; rises in chaos. At 100% a coup ousts you.",

		"throne.epigraph": "\"The stability of the state rests upon the edge of the saber.\"",
		"throne.tap": "Tap the Seal — fill the treasury",
		"throne.reform": "Nizam-i Cedid Reform",
		"throne.per_click": "per tap",
		"throne.frenzy_cd": "×%d in %d s",
		"throne.taps": "Taps",
		"prov.revenue": "HAZNA PER TAP",
		"prov.per_tap": "per tap",
		"prov.rising": "Empire Rising",
		"prov.declining": "Empire Declining",
		"prov.governed": "Governed Eyalets",
		"prov.souls": "Souls",
		"prov.invest": "Invest",
		"prov.suppress": "Suppress",
		"prov.fracture": "Unrest",
		"prov.lost": "SECEDED",
		"prov.core": "Imperial Heart",
		"inst.title": "Imperial Institutions",
		"inst.epigraph": "The pillars of the House of Osman must be reinforced to withstand the winds of change.",
		"inst.level": "Level",
		"inst.rank": "Rank",
		"inst.upgrade": "Upgrade",
		"inst.unlock": "Unlock",
		"inst.high_risk": "HIGH RISK",
		"inst.accelerate": "ACCELERATE REFORM",
		"inst.progress": "Progress",
		"inst.reform_done": "Reform complete",
		"ev.title": "The Record",
		"ev.subtitle": "The Imperial Record",
		"ev.epigraph": "\"Every decision carves the path of the House of Osman.\"",
		"ev.empty": "The record is empty. History is unwritten.",
		"ev.decree": "Imperial Decree",
		"ev.requirement": "Requirement",
		"ev.cost": "Cost",
		"prov.provisions": "Provisions",
		"prov.buy_food": "Buy grain",
		"prov.per_unit": "unit",
		"prov.granaries": "Granaries",
		"prov.upgrade_granaries": "Upgrade granaries",
		"prov.razed": "city ruined, development lost",
		"ev.envoy_title": "A Messenger Arrives",
		"ev.envoy_sub": "A sealed letter has reached the throne. It awaits your word, my lord.",
		"ev.open_letter": "Open the letter",
		"ev.your_state": "Your state",
		"ev.hold_hint": "Hold a choice to preview",
		"ev.result": "Likely outcome",

		"dyn.title": "The Sublime State",
		"dyn.protector": "PROTECTOR OF THE REALMS",
		"dyn.prestige": "IMPERIAL PRESTIGE",
		"dyn.next_rank": "Next Rank",
		"dyn.decrees": "Legacy Decrees",
		"dyn.bought": "UPGRADED",
		"dyn.buy": "BUY",
		"dyn.family": "Family Tree",
		"throne.diplomacy": "Diplomacy",
		"diplo.title": "Diplomacy",
		"diplo.hint": "Relations fade over time — maintain them with gold. Poor relations mean costly bread and border clashes.",
		"diplo.improve": "Improve",
		"diplo.worsen": "Worsen",
		"diplo.eff.trade_bad": "Trade routes closed: +%d%% bread price",
		"diplo.eff.trade_mid": "Heavy tolls: +%d%% bread price",
		"diplo.eff.trade_ok": "Trade flows freely",
		"diplo.eff.vassal": "Vassal: pays tribute, sends troops",
		"diplo.eff.border_bad": "Border raids inevitable",
		"diplo.eff.border_mid": "Border skirmishes rising",
		"diplo.eff.border_ok": "Border is calm",
		"diplo.vassal": "Vassal",
		"diplo.tariff": "Chumak caravan tolls: +%d%% to bread price",
		"diplo.tariff_none": "Trade routes are open — bread flows toll-free",
		"diplo.moscow": "Tsardom of Muscovy",
		"diplo.poland": "Polish-Lithuanian Commonwealth",
		"diplo.austria": "Austria",
		"diplo.persia": "Safavid Persia",
		"diplo.crimea": "Crimean Khanate",
		"dyn.you": "Sultan (you)",
		"dyn.reigned_until": "reigned until",
		"dyn.spouse": "Consort",
		"dyn.heir": "Heir",
		"dyn.no_spouse": "No consort yet",
		"dyn.empty_heir": "No heir",
		"dyn.deceased": "deceased",
		"dyn.deceased_f": "deceased",
		"dyn.wed": "Wedding",
		"dyn.wed_open": "Seek a bride",
		"dyn.no_wife": "No consort",
		"dyn.seek_title": "Seek a consort?",
		"dyn.seek_body": "Announce a search for a bride among the noble houses? It costs 10,000 hazna, after which offers of marriage will begin to arrive.",
		"dyn.seek_pay": "Pay",
		"dyn.seek_cancel": "Cancel",
		"dyn.seek_cta": "Find a wife",
		"dyn.seeking": "Seeking a consort…",
		"dyn.seek_started": "The search for a consort has begun — await offers.",
		"dyn.seek_poor": "Not enough hazna for the bride search.",
		"ev.skirmish_losses": "Skirmish losses — the army's trust is shaken:",
		"menu.title": "Sunset of the Crescent",
		"menu.play": "Play",
		"wheel.hazna_10k": "10 000 ⚜",
		"wheel.energy_2d": "⚡ 2 days",
		"wheel.debt_10k": "− 10 000 ⚜",
		"wheel.no_ads": "No ads",
		"wheel.wife_coupon": "Coupon − 80%",
		"wheel.amnesty": "Amnesty",
		"wheel.ad": "Ad",
		"wheel.debt_20k": "− 20 000 ⚜",
		"wheel.diplo_coupon": "Envoy coupon",
		"wheel.ad2": "Ad",
		"wheel.debt_50k": "− 50 000 ⚜",
		"wheel.energy_1d": "⚡ 1 day",
		"menu.wheel": "Wheel of Fortune",
		"menu.settings": "Settings",
		"menu.donate": "Support",
		"menu.wheel_ready": "Ready!",
		"menu.wheel_in": "In %s",
		"wheel.title": "Wheel of Fortune",
		"wheel.spin": "Spin the wheel",
		"wheel.back": "Back",
		"wheel.won": "You won:",
		"wheel.next": "Next spin in %s",
		"donate.title": "Support the Game",
		"donate.body": "Thank you for playing! You can support development by watching an ad or donating.",
		"donate.ad": "Watch an ad (+1,000 \u269C)",
		"donate.ad_soon": "Coming soon — after ads are wired up",
		"donate.support": "Support development",
		"energy.title": "Energy",
		"energy.full_in": "Full in %s",
		"energy.empty": "Energy depleted — the Sultan needs rest.",
		"energy.unlim": "Unlimited: %s",
		"debt.forgiven": "Debts forgiven!",
		"debt.amnesty_kept": "Amnesty gained — it will trigger on your first debt.",
		"ads.stub": "(test) Reward granted — ads will be connected later.",
		"ads.not_ready": "Ads are not available yet.",
		"ads.energy": "Full energy for an ad",
		"wheel.respin": "Spin again — for an ad",
		"wheel.double": "Double the prize — for an ad",
		"offline.double": "Double it for an ad",
		"over.second": "Second chance — for an ad",
		"donate.burn_debt": "Burn the debt — for an ad",
		"iap.title": "Purchases",
		"iap.soon": "Purchases will be available after the Google Play release.",
		"iap.noads": "Remove ads forever — $2.99",
		"iap.starter": "Starter pack — $1.99",
		"iap.hazna1": "Purse of hazna (20,000) — $0.99",
		"iap.hazna2": "Chest of hazna (40,000) — $2.99",
		"iap.hazna3": "Pasha's treasury (100,000) — $7.99",
		"iap.firman": "Golden Firman: +25% per tap — $3.99",
		"daily.title": "Daily reward:",
		"daily.d1": "+1,500 hazna",
		"daily.d2": "energy restored",
		"daily.d3": "the wheel is ready",
		"quest.done": "Quest complete:",
		"quest.plague": "Survive the plague",
		"quest.inst": "A level-3 institution",
		"quest.gen3": "Three generations",
		"quest.staff_cost": "Attending the war council costs %s ⚜",
		"dyn.wife_lost": "Consort lost",
		"dyn.born": "Heir born",
		"dyn.died": "Heir lost",
		"dyn.family_hint": "Consorts are chosen through rare events — up to four in the harem; a consort can be lost (plague, riot). A son and heir is born through an event; once grown he may take the throne — at your will, or by force when opposition runs high.",
		"dyn.new_reign": "Pass the Seal to the Heir",
		"dyn.new_reign_hint": "Raise your grown son to the throne and convert your achievements into Imperial Prestige. Decrees and prestige are kept; you then play as the son.",
		"dyn.gain": "Prestige from this reign",
		"dyn.heir_ready": "heir · ready to reign",
		"dyn.heir_growing": "The heir is still young — he can take the throne once he comes of age.",
		"dyn.need_heir": "You need a son and heir first — he is born through an event.",
		"dyn.crisis_pass": "The realm is in crisis. Pass the Seal to your son before he seizes the throne by force.",
		"dyn.no_adult_heir": "No grown heir to take the throne.",
		"dyn.future_wife": "future consort",
		"dyn.consort": "consort",
		"dyn.usurp": "The son has seized the throne!",
		"dyn.new_sultan": "New Sultan:",
		"dyn.sultan_prefix": "Sultan",
		"set.title": "Settings",
		"set.language": "Language",
		"set.music": "Music",
		"notif.energy": "Battery recharged — the state awaits you!",
		"notif.day1": "O great Padishah, the game awaits you!",
		"notif.day2": "The Janissaries revolt — PADISHAH, WHERE ARE YOU???",
		"notif.day3": "The Empire is burning — where is the Sultan?",
		"notif.day4": "The Divan has assembled without you — awaiting your word.",
		"notif.day5": "The harem is anxious, the heir weeps — return, my lord.",
		"notif.day6": "A messenger stands at the gate with a sealed letter — only you may break it.",
		"notif.day7": "The opposition whispers in the corners… someone must listen.",
		"notif.day8": "The treasury runs dry, the granaries fall silent. The realm awaits its master.",
		"notif.day9": "The azan sounds again from the minaret — is it not time to return?",

		"load.q1": "\"The stability of the state rests on the edge of a sabre.\"",
		"load.q2": "\"He who holds the treasury holds the crown.\"",
		"load.q3": "\"The empire is vast so long as the Sultan does not sleep.\"",
		"load.q4": "\"Bread is dearer than gold when the granaries are empty.\"",
		"load.q5": "\"The Janissaries keep two kettles: one for pilaf, one for mutiny.\"",
		"load.q6": "\"The cossack rides for plunder; the pasha rides for the cossack.\"",
		"load.q7": "\"A wise Sultan listens to the Divan and decides alone.\"",
		"load.q8": "\"Opposition whispers until hunger makes it scream.\"",
		"load.q9": "\"The House of Osman stands on three pillars: faith, army, and treasury.\"",
		"load.q10": "\"A messenger with bad news rides faster than one with good.\"",
		"load.q11": "\"A province without a governor is a horse without reins.\"",
		"load.q12": "\"He who hurries to inherit digs his own grave.\"",
		"load.q13": "\"The plague does not ask leave to enter the palace.\"",
		"load.q14": "\"A fed street is a silent street.\"",
		"load.q15": "\"Empires fall not to enemies, but to their own shadows.\"",
		"load.progress": "Loading",
		"set.fps": "FPS",
		"set.voice": "Voiceover",
		"set.sfx": "Sound effects",
		"set.on": "On",
		"set.off": "Off",
		"set.reset": "Reset progress",
		"set.about": "About",
		"set.close": "Close",
		"set.about_text": "Sunset of the Crescent — a mobile strategy about the managed dying of the Ottoman Empire. A work of fiction inspired by real events. Spec v1.1.",
		"set.offline": "While you were away, the treasury grew:",
		"common.year": "YEAR",
		"common.confirm": "Confirm",
		"common.cancel": "Cancel",
	}
}

func t(key: String) -> String:
	var table: Dictionary = DATA.get(lang, DATA["ru"])
	if table.has(key):
		return table[key]
	# fallback на русский, затем на сам ключ
	if DATA["ru"].has(key):
		return DATA["ru"][key]
	return key

func set_lang(new_lang: String) -> void:
	if new_lang != lang and DATA.has(new_lang):
		lang = new_lang
		language_changed.emit()
