extends Node
## Loc — простая локализация по ключам (ТЗ §29). По умолчанию русский.
## Весь UI-текст идёт через t("key") — никаких хардкод-строк в логике.

signal language_changed

var lang := "ru"

const DATA := {
	"ru": {
		# Навигация (§5.2 — RU-сборка)
		"nav.throne": "Трон",
		"nav.provinces": "Эялеты",
		"nav.institutions": "Институты",
		"nav.events": "Летопись",
		"nav.dynasty": "Династия",
		# Ресурсы (§8)
		"res.hazna": "Хазна",
		"res.stability": "Стабильность",
		"res.army": "Армия",
		"res.loyalty": "Лояльность",
		"res.food": "Еда",
		"res.opposition": "Оппозиция",
		"res.fracture": "Трещина",
		"res.development": "Развитие",
		"res.pressure": "Давление",
		"leg.pressure": "Внешнее давление держав. Растёт со временем; ускоряет падение стабильности, расход еды и распад провинций.",

		"sys.coup": "Дворцовый переворот! Вас свергли.",
		"over.title": "Вас свергли",
		"over.sub": "Толпа и янычары низложили султана. Ваше правление окончено — но новый дом может подняться из пепла.",
		"over.restart": "Начать сначала",

		"set.legend": "Показатели",
		"leg.hazna": "Казна. Копится за касания Печати; тратится на вложения, институты и решения событий.",
		"leg.stability": "Порядок в державе. Падает от внешнего давления и трещин; при 0 оппозиция растёт стремительно.",
		"leg.army": "Военная мощь. Нужна для подавления провинций и жёстких вариантов в событиях.",
		"leg.loyalty": "Верность подданных. Низкая — ускоряет трещины провинций и рост оппозиции.",
		"leg.food": "Продовольствие. Зависит от развития провинций; мало — падает стабильность и начинаются бунты.",
		"leg.opposition": "Сила недовольных. Каждое решение её двигает; растёт при хаосе. 100% — дворцовый переворот.",

		# Трон
		"throne.epigraph": "«Стабильность государства держится на острие сабли.»",
		"throne.tap": "Коснись Печати — наполни казну",
		"throne.reform": "Реформа Низам-ı Джедид",
		"throne.per_click": "за касание",
		"throne.taps": "Касаний",
		# Эялеты
		"prov.revenue": "ХАЗНА ЗА КАСАНИЕ",
		"prov.per_tap": "за касание",
		"prov.rising": "Империя крепнет",
		"prov.declining": "Империя угасает",
		"prov.governed": "Управляемые эялеты",
		"prov.souls": "душ",
		"prov.invest": "Вложить",
		"prov.suppress": "Подавить",
		"prov.fracture": "Трещина",
		"prov.lost": "ОТКОЛОЛАСЬ",
		"prov.core": "Ядро империи",
		# Институты
		"inst.title": "Имперские институты",
		"inst.epigraph": "Опоры Дома Османа должны выдержать ветры перемен.",
		"inst.level": "Уровень",
		"inst.rank": "Ранг",
		"inst.upgrade": "Развить",
		"inst.high_risk": "ВЫСОКИЙ РИСК",
		"inst.accelerate": "УСКОРИТЬ РЕФОРМУ",
		"inst.progress": "прогресс",
		"inst.reform_done": "Реформа завершена",
		# Летопись / события
		"ev.title": "Летопись",
		"ev.subtitle": "Имперская хроника",
		"ev.epigraph": "«Каждое решение прокладывает путь Дома Османа.»",
		"ev.empty": "Хроника пуста. История ещё не написана.",
		"ev.decree": "Имперский декрет",
		"ev.requirement": "Требование",
		"ev.cost": "Цена",
		"prov.provisions": "Снабжение",
		"prov.buy_food": "Купить еду",
		"prov.granaries": "Амбары",
		"prov.upgrade_granaries": "Улучшить амбары",
		"prov.razed": "город разрушен, развитие утрачено",
		"ev.envoy_title": "Прибыл гонец",
		"ev.envoy_sub": "К трону доставлено запечатанное письмо. Оно ждёт вашего слова, повелитель.",
		"ev.open_letter": "Открыть письмо",
		"ev.your_state": "Ваше положение",
		"ev.hold_hint": "Зажми вариант — увидишь исход",
		"ev.result": "Возможный исход",

		# Династия
		"dyn.title": "Высокая Порта",
		"dyn.protector": "ЗАЩИТНИК ПРЕДЕЛОВ",
		"dyn.prestige": "ИМПЕРСКИЙ ПРЕСТИЖ",
		"dyn.next_rank": "Следующий ранг",
		"dyn.decrees": "Декреты наследия",
		"dyn.bought": "ПОЛУЧЕНО",
		"dyn.buy": "КУПИТЬ",
		"dyn.new_reign": "Передать Печать наследнику",
		"dyn.new_reign_hint": "Завершить правление и обратить достижения в Имперский престиж. Декреты и престиж сохранятся.",
		"dyn.gain": "Престижа за правление",
		# Настройки
		"set.title": "Настройки",
		"set.language": "Язык",
		"set.music": "Музыка",
		"set.on": "Вкл",
		"set.off": "Выкл",
		"set.reset": "Сбросить прогресс",
		"set.about": "Об игре",
		"set.close": "Закрыть",
		"set.about_text": "Sunset of the Crescent — мобильная стратегия об управляемом умирании Османской империи. Художественное произведение по мотивам реальных событий. ТЗ v1.1.",
		"set.offline": "Пока тебя не было, казна пополнялась:",
		# Общее
		"common.year": "ГОД",
		"common.confirm": "Подтвердить",
		"common.cancel": "Отмена",
	},
	"en": {
		"nav.throne": "Throne",
		"nav.provinces": "Provinces",
		"nav.institutions": "Institutions",
		"nav.events": "Events",
		"nav.dynasty": "Dynasty",
		"res.hazna": "Hazna",
		"res.stability": "Stability",
		"res.army": "Army",
		"res.loyalty": "Loyalty",
		"res.food": "Food",
		"res.opposition": "Opposition",
		"res.fracture": "Fracture",
		"res.development": "Development",
		"res.pressure": "Pressure",
		"leg.pressure": "Foreign pressure on the empire. Rises over time; speeds stability loss, food drain and province collapse.",

		"sys.coup": "Palace coup! You have been overthrown.",
		"over.title": "You Have Been Overthrown",
		"over.sub": "The mob and the Janissaries have deposed the Sultan. Your reign is over — but a new house may rise from the ashes.",
		"over.restart": "Start over",

		"set.legend": "Indicators",
		"leg.hazna": "Treasury. Earned by tapping the Seal; spent on investments, institutions and event choices.",
		"leg.stability": "Order in the realm. Falls from outside pressure and fractures; at 0 opposition surges fast.",
		"leg.army": "Military power. Needed to suppress provinces and unlock harsh event options.",
		"leg.loyalty": "Loyalty of subjects. When low it speeds province fractures and opposition.",
		"leg.food": "Food supply. Driven by province development; when low, stability drops and riots begin.",
		"leg.opposition": "Strength of the discontent. Every decision shifts it; rises in chaos. At 100% a coup ousts you.",

		"throne.epigraph": "\"The stability of the state rests upon the edge of the saber.\"",
		"throne.tap": "Tap the Seal — fill the treasury",
		"throne.reform": "Nizam-i Cedid Reform",
		"throne.per_click": "per tap",
		"throne.taps": "Taps",
		"prov.revenue": "HAZNA PER TAP",
		"prov.per_tap": "per tap",
		"prov.rising": "Empire Rising",
		"prov.declining": "Empire Declining",
		"prov.governed": "Governed Eyalets",
		"prov.souls": "Souls",
		"prov.invest": "Invest",
		"prov.suppress": "Suppress",
		"prov.fracture": "Fracture",
		"prov.lost": "SECEDED",
		"prov.core": "Imperial Heart",
		"inst.title": "Imperial Institutions",
		"inst.epigraph": "The pillars of the House of Osman must be reinforced to withstand the winds of change.",
		"inst.level": "Level",
		"inst.rank": "Rank",
		"inst.upgrade": "Upgrade",
		"inst.high_risk": "HIGH RISK",
		"inst.accelerate": "ACCELERATE REFORM",
		"inst.progress": "Progress",
		"inst.reform_done": "Reform complete",
		"ev.title": "The Record",
		"ev.subtitle": "The Imperial Record",
		"ev.epigraph": "\"Every decision carves the path of the House of Osman.\"",
		"ev.empty": "The record is empty. History is unwritten.",
		"ev.decree": "Imperial Decree",
		"ev.requirement": "Requirement",
		"ev.cost": "Cost",
		"prov.provisions": "Provisions",
		"prov.buy_food": "Buy food",
		"prov.granaries": "Granaries",
		"prov.upgrade_granaries": "Upgrade granaries",
		"prov.razed": "city ruined, development lost",
		"ev.envoy_title": "A Messenger Arrives",
		"ev.envoy_sub": "A sealed letter has reached the throne. It awaits your word, my lord.",
		"ev.open_letter": "Open the letter",
		"ev.your_state": "Your state",
		"ev.hold_hint": "Hold a choice to preview",
		"ev.result": "Likely outcome",

		"dyn.title": "The Sublime State",
		"dyn.protector": "PROTECTOR OF THE REALMS",
		"dyn.prestige": "IMPERIAL PRESTIGE",
		"dyn.next_rank": "Next Rank",
		"dyn.decrees": "Legacy Decrees",
		"dyn.bought": "UPGRADED",
		"dyn.buy": "BUY",
		"dyn.new_reign": "Pass the Seal to the Heir",
		"dyn.new_reign_hint": "End this reign and convert your achievements into Imperial Prestige. Decrees and prestige are kept.",
		"dyn.gain": "Prestige from this reign",
		"set.title": "Settings",
		"set.language": "Language",
		"set.music": "Music",
		"set.on": "On",
		"set.off": "Off",
		"set.reset": "Reset progress",
		"set.about": "About",
		"set.close": "Close",
		"set.about_text": "Sunset of the Crescent — a mobile strategy about the managed dying of the Ottoman Empire. A work of fiction inspired by real events. Spec v1.1.",
		"set.offline": "While you were away, the treasury grew:",
		"common.year": "YEAR",
		"common.confirm": "Confirm",
		"common.cancel": "Cancel",
	}
}

func t(key: String) -> String:
	var table: Dictionary = DATA.get(lang, DATA["ru"])
	if table.has(key):
		return table[key]
	# fallback на русский, затем на сам ключ
	if DATA["ru"].has(key):
		return DATA["ru"][key]
	return key

func set_lang(new_lang: String) -> void:
	if new_lang != lang and DATA.has(new_lang):
		lang = new_lang
		language_changed.emit()
